#@ load("/random.star", "seed", "password", "token", "haikunate")

#@ state = seed("mysecret")

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  password-1: #@ password(state)
  password-2: #@ password(state, 8)
  token-1: #@ token(state)
  token-2: #@ token(state, 32)
  hostname-1: #@ haikunate(state)
  hostname-2: #@ haikunate(state, token_length=10, token_hex=True)
