#@ load("@ytt:data", "data")
#@ load("/random.star", "seed", "password")

#@ state = seed("mysecret-3")

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-3
type: Opaque
stringData:
  password-1: #@ data.values.password1 if data.values.password1 != None else password(state)
  password-2: #@ data.values.password2 if data.values.password2 != None else password(state)
