#@ load("/random.star", "seed", "random")

#@ state = seed()

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-1a
type: Opaque
stringData:
  password-1: #@ str(random(state))
  password-2: #@ str(random(state))
  password-3: #@ str(random(state))
